apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: aap-kalkulator-frontend
    namespace: aap
    labels:
        team: aap
spec:
    port: 3000
    image: { { image } }
    ingresses:
        - https://aap-kalkulator.dev.nav.no
        - https://aap-kalkulator.ekstern.dev.nav.no
