apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: aap-kalkulator-frontend
    namespace: aap
    labels:
        team: aap
spec:
    port: 3000
    image: {{ image }}
    ingresses:
    {{#each ingresses as |url|}}
        - {{url}}
    {{/each}}
    env: 
    {{#each env}}
        - name: {{this.name}}
          value: {{this.value}}
    {{/each}}

