apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: aap-kalkulator-frontend
    namespace: aap
    labels:
        team: aap
spec:
    port: 3000
    image: {{ image }}
    liveness:
        path: "/aap/kalkulator/api/internal/isAlive"
        initialDelay: 20
        timeout: 60
    readiness:
        path: "/aap/kalkulator/api/internal/isReady"
        initialDelay: 20
        timeout: 60
    replicas:
        min: 2
        max: 2
    resources:
        requests:
            cpu: 200m
            memory: 256Mi
        limits:
            memory: 256Mi
    ingresses:
    {{#each ingresses as |url|}}
        - {{url}}
    {{/each}}
    filesFrom:
      - emptyDir:
          medium: Memory
        mountPath: /app/.next/cache
    accessPolicy:
        outbound:
            rules:
              - application: nav-dekoratoren
                namespace: personbruker
            external:
                - host: "g.nav.no"
    env: 
    {{#each env}}
        - name: {{this.name}}
          value: {{this.value}}
    {{/each}}

