name: "Build and deploy aap-kalkulator to dev"
on:
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  APP: aap-kalkulator-frontend
  IMAGE_BASE: ghcr.io/${{ github.repository }}
jobs:
  build:
    name: Bygg og publiser Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    outputs:
      image: ${{ steps.bygg.outputs.image }}
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-node@v3"
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
      - name: "install dependencies"
        run: "npm ci"
        env:
          NODE_AUTH_TOKEN: "${{ secrets.READER_TOKEN }}"

      - name: test application
        run: npm test

      - name: hent tidsstempel
        run: echo "NEXT_PUBLIC_LAST_UPDATED=$(date +%m-%d-%Y)" > .env.local

      - name: Setter tag-navn
        run: echo "TAG=$(date +%m-%d-%Y)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Setter image-navn
        run: echo "IMAGE=$(echo $IMAGE_BASE):$(echo $TAG)" >> $GITHUB_ENV

      - name: Bygg applikasjon
        id: bygg
        run: |
          echo "image=${{ env.IMAGE }}" >> $GITHUB_OUTPUT
          npm run build

      - name: upload to CDN
        uses: navikt/frontend/actions/cdn-upload/v1@main
        with:
          cdn-team-name: aap
          source: ./.next/static
          destination: '/aap-kalkulator-frontend/_next'

      - name: Docker login
        run:  echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin

      - name: Bygg og publiser docker image
        run: |
          docker build . -t ${IMAGE}
          docker push ${IMAGE}


  deploy:
    strategy:
      matrix:
        cluster: [ dev-gcp ]
    name: Deploy til ${{matrix.cluster}}
    needs: [build]
    runs-on: ubuntu-latest
    env:
      PRINT_PAYLOAD: true
      APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      RESOURCE: nais.yaml
      CLUSTER: ${{matrix.cluster}}
      VARS: .nais/${{matrix.cluster}}.yaml
      IMAGE: ${{needs.build.outputs.image}}
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@master


