name: Merge Dependabot pull requester
on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 8 * * 1-5"

jobs:
  merge-dependabot-pr:
    uses: navikt/aap-workflows/.github/workflows/merge-dependabot-pr.yml@main
    permissions:
      actions: write
      checks: read
      contents: write
      pull-requests: write
      statuses: read
