name: "Build and test PR"
on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '**.md'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  APP: aap-kalkulator-frontend
  IMAGE_BASE: ghcr.io/${{ github.repository }}
jobs:
  timestamp:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      lastupdated: ${{ steps.settimestamp.outputs.last_updated }}
    steps:
      - name: Lag timestamp
        id: settimestamp
        run: |
          last_updated="$(date +%m-%d-%Y)"
          echo "last_updated: $last_updated"
          echo "last_updated=$last_updated" >> $GITHUB_OUTPUT
  buildProd:
    uses: navikt/aap-workflows/.github/workflows/frontend-next-build.yml@main
    needs: timestamp
    permissions:
      contents: read
      id-token: write
      packages: write
    secrets: inherit
    with:
      cluster: prod-gcp
      appname: 'aap-kalkulator-frontend'
      playwright: true
      cdn: true
      dynamicenv: NEXT_PUBLIC_LAST_UPDATED=${{ needs.timestamp.outputs.lastupdated}}
