name: Push
on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '**.md'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  APP: aap-kalkulator-frontend
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  IMAGE_BASE: ghcr.io/${{ github.repository }}
jobs:
  build-and-publish:
    name: Bygg og publiser Docker image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.bygg.outputs.image }}
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-node@v3"
        with:
          node-version: "16"
          registry-url: "https://npm.pkg.github.com"
      - name: "install dependencies"
        run: "npm ci"
        env:
          NODE_AUTH_TOKEN: "${{ secrets.READER_TOKEN }}"

      - name: test application
        run: npm test
